concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Runner Dashboard Kepegawaian Pusdatin PU"
  url = "https://git-repo.pu.go.id"
  id = 34
  token = "glrt-a4-kM0R855QRec21-4HITW86MQpwOmJnCnQ6Mwp1OjkwEQ.01.1a00lqkls"
  token_obtained_at = 2026-06-17T07:57:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
      AssumeRoleMaxConcurrency = 0
    [runners.cache.gcs]
    [runners.cache.azure]
